# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-23 17:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


def forwards(self, orm):
        from django.core.management import call_command
        call_command("loaddata", "fixtures/department.json")
        call_command("loaddata", "fixtures/employee.json")
        call_command("loaddata", "fixtures/user.json")

class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.Department')),
            ],
        ),
        migrations.RunPython(forwards),
    ]
